auth0:
  audience: ${AUTH0_AUDIENCE:https://auth-microservice/api}
spring:
  application:
    name: resource-service-with-auth-example
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI:https://dev-p17haprzong06zow.us.auth0.com/}
  datasource:
    url: ${SPRING_DATASOURCE_URL_AUTHORIZATION:jdbc:postgresql://localhost:5432/mibase}
    username: ${SPRING_DATASOURCE_USERNAME_AUTHORIZATION:miusuario}
    password: ${SPRING_DATASOURCE_PASSWORD_AUTHORIZATION:mipassword}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true